name: Install ubuntu-desktop
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Install ubuntu-desktop package
        run: sudo apt-get update; sudo apt-get install ubuntu-desktop; sudo apt-get update
