#===============================================================================
#          FILE:  ubuntu-firstrun-config.bash
#         USAGE:  sudo bash ./ubuntu-firstrun-config.bash
#   DESCRIPTION:  The script enables installation and configuration of some
#                 essential apps and utilties that make your Ubuntu more
#                 useful and powerful.
#       OPTIONS:  ---
#  REQUIREMENTS:  zenity (preinstalled with Ubuntu)
#         NOTES:  ---
#        AUTHOR:  wiktor2200, https://github.com/wiktor2200
#          REPO:  https://github.com/wiktor2200/Ubuntu-firstrun-config
#       CREATED:  2018-06-12
#       UPDATED:  2022-07-30
#===============================================================================
name: Check Bash scripts
on: [pull_request]

jobs:
  perform-upgrade:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run perform-upgrade
        run: sudo bash ./scripts/perform-upgrade
  enable-upgrade-notifications:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run enable-upgrade-notifications
        run: sudo bash ./scripts/enable-upgrade-notifications
  perform-cleanup:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run perform-cleanup
        run: sudo bash ./scripts/perform-cleanup
  uninstall-garbage-packages:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run uninstall-garbage-packages
        run: sudo bash ./scripts/uninstall-garbage-packages
  install-libreoffice:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-libreoffice
        run: sudo bash ./scripts/install-libreoffice
  install-vs-code:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-vs-code
        run: sudo bash ./scripts/install-vs-code
  install-vlc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-vlc
        run: sudo bash ./scripts/install-vlc
  install-gimp:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-gimp
        run: sudo bash ./scripts/install-gimp
  install-password-manager:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-password-manager
        run: sudo bash ./scripts/install-password-manager
  install-archives-tools:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-archives-tools
        run: sudo bash ./scripts/install-archives-tools
  install-codecs:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-codecs
        run: sudo bash ./scripts/install-codecs
  install-gnome-tools:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-gnome-tools
        run: sudo bash ./scripts/install-gnome-tools
  install-language-packages:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-language-packages
        run: sudo bash ./scripts/install-language-packages
  install-system-utilties:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-system-utilties
        run: sudo bash ./scripts/install-system-utilties
  install-backup-tools:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-backup-tools
        run: sudo bash ./scripts/install-backup-tools
  replace-snap-packages:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run replace-snap-packages
        run: sudo bash ./scripts/replace-snap-packages
  install-fslint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-fslint
        run: sudo bash ./scripts/install-fslint
  install-bleachbit:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-bleachbit
        run: sudo bash ./scripts/install-bleachbit
  uninstall-ubuntu-dock:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run uninstall-ubuntu-dock
        run: sudo bash ./scripts/uninstall-ubuntu-dock
  install-docker:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-docker
        run: sudo bash ./scripts/install-docker
  install-virtualbox:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-virtualbox
        run: sudo bash ./scripts/install-virtualbox
  install-calibre:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-calibre
        run: sudo bash ./scripts/install-calibre
  install-ocr:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-ocr
        run: sudo bash ./scripts/install-ocr
  install-pdf-tools:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-pdf-tools
        run: sudo bash ./scripts/install-pdf-tools
  install-qownnotes:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-qownnotes
        run: sudo bash ./scripts/install-qownnotes
  fix-top-panel-icons:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run fix-top-panel-icons
        run: sudo bash ./scripts/fix-top-panel-icons
  install-dia:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-dia
        run: sudo bash ./scripts/install-dia
  install-gnome-paint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-gnome-paint
        run: sudo bash ./scripts/install-gnome-paint
  install-inkscape:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-inkscape
        run: sudo bash ./scripts/install-inkscape
  install-battery-support:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-battery-support
        run: sudo bash ./scripts/install-battery-support
  install-scanner-support:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-scanner-support
        run: sudo bash ./scripts/install-scanner-support
  install-webcam-cheese:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-webcam-cheese
        run: sudo bash ./scripts/install-webcam-cheese
  install-atom:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-atom
        run: sudo bash ./scripts/install-atom
  install-hex-bless-editor:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-hex-bless-editor
        run: sudo bash ./scripts/install-hex-bless-editor
  install-qtcreator:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-qtcreator
        run: sudo bash ./scripts/install-qtcreator
  install-hex-gnome-editor:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-hex-gnome-editor
        run: sudo bash ./scripts/install-hex-gnome-editor
  install-amarok:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-amarok
        run: sudo bash ./scripts/install-amarok
  install-audacity:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-audacity
        run: sudo bash ./scripts/install-audacity
  install-sysadmin-network-tools:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-sysadmin-network-tools
        run: sudo bash ./scripts/install-sysadmin-network-tools
  enable-tmp-ram:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run enable-tmp-ram
        run: sudo bash ./scripts/enable-tmp-ram
  remove-swapfile:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run remove-swapfile
        run: sudo bash ./scripts/remove-swapfile
  install-photo-utils:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-photo-utils
        run: sudo bash ./scripts/install-photo-utils
  install-digikam:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-digikam
        run: sudo bash ./scripts/install-digikam
  install-dropbox:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-dropbox
        run: sudo bash ./scripts/install-dropbox
  install-nextcloud:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-nextcloud
        run: sudo bash ./scripts/install-nextcloud
  install-owncloud:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-owncloud
        run: sudo bash ./scripts/install-owncloud
  install-cinnamon:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-cinnamon
        run: sudo bash ./scripts/install-cinnamon
  install-chromium:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-chromium
        run: sudo bash ./scripts/install-chromium
  install-antivir:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-antivir
        run: sudo bash ./scripts/install-antivir
  install-desktop-recorder:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-desktop-recorder
        run: sudo bash ./scripts/install-desktop-recorder
  install-qalculate:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-qalculate
        run: sudo bash ./scripts/install-qalculate
  install-slack:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-slack
        run: sudo bash ./scripts/install-slack
  install-taskcoach:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-taskcoach
        run: sudo bash ./scripts/install-taskcoach
  install-tellico:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-tellico
        run: sudo bash ./scripts/install-tellico
  install-thunderbird:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-thunderbird
        run: sudo bash ./scripts/install-thunderbird
  install-amd-nvidia-drivers:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-amd-nvidia-drivers
        run: sudo bash ./scripts/install-amd-nvidia-drivers
  install-mkusb:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-mkusb
        run: sudo bash ./scripts/install-mkusb
  install-cd-dvd-burner:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-cd-dvd-burner
        run: sudo bash ./scripts/install-cd-dvd-burner
  install-fzf:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-fzf
        run: sudo bash ./scripts/install-fzf
  install-guake:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-guake
        run: sudo bash ./scripts/install-guake
  install-acetoneiso:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-acetoneiso
        run: sudo bash ./scripts/install-acetoneiso
  install-firejail:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-firejail
        run: sudo bash ./scripts/install-firejail
  install-synaptic:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run install-synaptic
        run: sudo bash ./scripts/install-synaptic
  replace-nautilus-nemo:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run replace-nautilus-nemo
        run: sudo bash ./scripts/replace-nautilus-nemo
  replace-gedit-pluma:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run replace-gedit-pluma
        run: sudo bash ./scripts/replace-gedit-pluma
  set-grub:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run set-grub
        run: sudo bash ./scripts/set-grub
  show-hidden-autostart-entries:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run show-hidden-autostart-entries
        run: sudo bash ./scripts/show-hidden-autostart-entries
  uninstall-old-1604-dependencies:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run uninstall-old-1604-dependencies
        run: sudo bash ./scripts/uninstall-old-1604-dependencies
