#===============================================================================
#          FILE:  ubuntu-firstrun-config.bash
#         USAGE:  sudo bash ./ubuntu-firstrun-config.bash
#   DESCRIPTION:  The script enables installation and configuration of some
#                 essential apps and utilties that make your Ubuntu more
#                 useful and powerful.
#       OPTIONS:  ---
#  REQUIREMENTS:  zenity (preinstalled with Ubuntu)
#         NOTES:  ---
#        AUTHOR:  wiktor2200, https://github.com/wiktor2200
#          REPO:  https://github.com/wiktor2200/Ubuntu-firstrun-config
#       CREATED:  2018-06-12
#       UPDATED:  2022-07-30
#===============================================================================
name: Check Bash scripts
on: [pull_request]

jobs:
  check_bash_scripts:
    runs-on: ubuntu-22.04
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: Run perform-upgrade
        run: sudo bash ./scripts/perform-upgrade
      - name: Run enable-upgrade-notifications
        run: sudo bash ./scripts/enable-upgrade-notifications
      - name: Run perform-cleanup
        run: sudo bash ./scripts/perform-cleanup
      - name: Run uninstall-garbage-packages
        run: sudo bash ./scripts/uninstall-garbage-packages
      - name: Run install-libreoffice
        run: sudo bash ./scripts/install-libreoffice
      - name: Run install-vs-code
        run: sudo bash ./scripts/install-vs-code
      - name: Run install-vlc
        run: sudo bash ./scripts/install-vlc
      - name: Run install-gimp
        run: sudo bash ./scripts/install-gimp
      - name: Run install-password-manager
        run: sudo bash ./scripts/install-password-manager
      - name: Run install-archives-tools
        run: sudo bash ./scripts/install-archives-tools
      - name: Run install-codecs
        run: sudo bash ./scripts/install-codecs
      - name: Run install-gnome-tools
        run: sudo bash ./scripts/install-gnome-tools
      - name: Run install-language-packages
        run: sudo bash ./scripts/install-language-packages
      - name: Run install-system-utilties
        run: sudo bash ./scripts/install-system-utilties
      - name: Run install-backup-tools
        run: sudo bash ./scripts/install-backup-tools
      - name: Run replace-snap-packages
        run: sudo bash ./scripts/replace-snap-packages
      - name: Run install-fslint
        run: sudo bash ./scripts/install-fslint
      - name: Run install-bleachbit
        run: sudo bash ./scripts/install-bleachbit
      - name: Run uninstall-ubuntu-dock
        run: sudo bash ./scripts/uninstall-ubuntu-dock
      - name: Run install-docker
        run: sudo bash ./scripts/install-docker
      - name: Run install-virtualbox
        run: sudo bash ./scripts/install-virtualbox
      - name: Run install-calibre
        run: sudo bash ./scripts/install-calibre
      - name: Run install-ocr
        run: sudo bash ./scripts/install-ocr
      - name: Run install-pdf-tools
        run: sudo bash ./scripts/install-pdf-tools
      - name: Run install-qownnotes
        run: sudo bash ./scripts/install-qownnotes
      - name: Run fix-top-panel-icons
        run: sudo bash ./scripts/fix-top-panel-icons
      - name: Run install-dia
        run: sudo bash ./scripts/install-dia
      - name: Run install-gnome-paint
        run: sudo bash ./scripts/install-gnome-paint
      - name: Run install-inkscape
        run: sudo bash ./scripts/install-inkscape
      - name: Run install-battery-support
        run: sudo bash ./scripts/install-battery-support
      - name: Run install-scanner-support
        run: sudo bash ./scripts/install-scanner-support
      - name: Run install-webcam-cheese
        run: sudo bash ./scripts/install-webcam-cheese
      - name: Run install-atom
        run: sudo bash ./scripts/install-atom
      - name: Run install-hex-bless-editor
        run: sudo bash ./scripts/install-hex-bless-editor
      - name: Run install-qtcreator
        run: sudo bash ./scripts/install-qtcreator
      - name: Run install-hex-gnome-editor
        run: sudo bash ./scripts/install-hex-gnome-editor
      - name: Run install-amarok
        run: sudo bash ./scripts/install-amarok
      - name: Run install-audacity
        run: sudo bash ./scripts/install-audacity
      - name: Run install-sysadmin-network-tools
        run: sudo bash ./scripts/install-sysadmin-network-tools
      - name: Run enable-tmp-ram
        run: sudo bash ./scripts/enable-tmp-ram
      - name: Run remove-swapfile
        run: sudo bash ./scripts/remove-swapfile
      - name: Run install-photo-utils
        run: sudo bash ./scripts/install-photo-utils
      - name: Run install-digikam
        run: sudo bash ./scripts/install-digikam
      - name: Run install-dropbox
        run: sudo bash ./scripts/install-dropbox
      - name: Run install-nextcloud
        run: sudo bash ./scripts/install-nextcloud
      - name: Run install-owncloud
        run: sudo bash ./scripts/install-owncloud
      - name: Run install-cinnamon
        run: sudo bash ./scripts/install-cinnamon
      - name: Run install-chromium
        run: sudo bash ./scripts/install-chromium
      - name: Run install-antivir
        run: sudo bash ./scripts/install-antivir
      - name: Run install-desktop-recorder
        run: sudo bash ./scripts/install-desktop-recorder
      - name: Run install-qalculate
        run: sudo bash ./scripts/install-qalculate
      - name: Run install-slack
        run: sudo bash ./scripts/install-slack
      - name: Run install-taskcoach
        run: sudo bash ./scripts/install-taskcoach
      - name: Run install-tellico
        run: sudo bash ./scripts/install-tellico
      - name: Run install-thunderbird
        run: sudo bash ./scripts/install-thunderbird
      - name: Run install-amd-nvidia-drivers
        run: sudo bash ./scripts/install-amd-nvidia-drivers
      - name: Run install-mkusb
        run: sudo bash ./scripts/install-mkusb
      - name: Run install-cd-dvd-burner
        run: sudo bash ./scripts/install-cd-dvd-burner
      - name: Run install-fzf
        run: sudo bash ./scripts/install-fzf
      - name: Run install-guake
        run: sudo bash ./scripts/install-guake
      - name: Run install-acetoneiso
        run: sudo bash ./scripts/install-acetoneiso
      - name: Run install-firejail
        run: sudo bash ./scripts/install-firejail
      - name: Run install-synaptic
        run: sudo bash ./scripts/install-synaptic
      - name: Run replace-nautilus-nemo
        run: sudo bash ./scripts/replace-nautilus-nemo
      - name: Run replace-gedit-pluma
        run: sudo bash ./scripts/replace-gedit-pluma
      - name: Run set-grub
        run: sudo bash ./scripts/set-grub
      - name: Run show-hidden-autostart-entries
        run: sudo bash ./scripts/show-hidden-autostart-entries
      - name: Run uninstall-old-1604-dependencies
        run: sudo bash ./scripts/uninstall-old-1604-dependencies
