#===============================================================================
#          FILE:  ubuntu-firstrun-config.bash
#         USAGE:  sudo bash ./ubuntu-firstrun-config.bash
#   DESCRIPTION:  The script enables installation and configuration of some
#                 essential apps and utilties that make your Ubuntu more
#                 useful and powerful.
#       OPTIONS:  ---
#  REQUIREMENTS:  zenity (preinstalled with Ubuntu)
#         NOTES:  ---
#        AUTHOR:  wiktor2200, https://github.com/wiktor2200
#          REPO:  https://github.com/wiktor2200/Ubuntu-firstrun-config
#       CREATED:  2018-06-12
#       UPDATED:  2022-07-30
#===============================================================================
name: Check Bash scripts
on: [pull_request]

jobs:
  perform-upgrade:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run perform-upgrade
        run: sudo bash ./scripts/perform-upgrade
  enable-upgrade-notifications:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run enable-upgrade-notifications
        run: sudo bash ./scripts/enable-upgrade-notifications
  perform-cleanup:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run perform-cleanup
        run: sudo bash ./scripts/perform-cleanup
