#===============================================================================
#          FILE:  ubuntu-firstrun-config.bash
#         USAGE:  sudo bash ./ubuntu-firstrun-config.bash
#   DESCRIPTION:  The script enables installation and configuration of some
#                 essential apps and utilties that make your Ubuntu more
#                 useful and powerful.
#       OPTIONS:  ---
#  REQUIREMENTS:  zenity (preinstalled with Ubuntu)
#         NOTES:  ---
#        AUTHOR:  wiktor2200, https://github.com/wiktor2200
#          REPO:  https://github.com/wiktor2200/Ubuntu-firstrun-config
#       CREATED:  2018-06-12
#       UPDATED:  2022-08-05
#===============================================================================
name: Check Bash scripts
on: [pull_request]

jobs:
  replace-gedit-pluma:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/install-ubuntu-desktop.yml
      - name: Run replace-gedit-pluma
        run: sudo apt-get update; sudo bash ./scripts/replace-gedit-pluma