name: Install ubuntu-desktop

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install ubuntu-desktop package
        run: sudo apt-get update; sudo apt-get install ubuntu-desktop; sudo apt-get update
